services:
  ssh-578.cyrhades.fr:
    container_name: ssh-578
    build:
      context: ./.docker/ssh
      args:
        LANGUAGE: ${LANGUAGE:-fr}
    labels:
      ho.ctf.cyrhades: "challenge"
      ho.ctf.cyrhades.webssh: "1"
    environment:
      SSH_HOSTNAME: "ssh-578.cyrhades.fr"
      SSH_PORT: 22
      SSH_USERNAME: "cyrhades"
      SSH_PASSWORD: "secret"
    restart: unless-stopped
  atomic-secable.cyrhades.fr:
    image: anssi/fcsc2025-hardware-atomic-secable:latest
